name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install TA-Lib C library
      run: |
        # Install build dependencies
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf libtool pkg-config

        # Download and install TA-Lib from source
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        
        # Update linker cache
        sudo ldconfig
        
        # Verify installation
        ls -la /usr/lib/libta_lib*
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine wheel setuptools
        
        # Install TA-Lib Python wrapper
        export TA_LIBRARY_PATH=/usr/lib
        export TA_INCLUDE_PATH=/usr/include
        python -m pip install numpy pandas  # Dependencies for TA-Lib
        python -m pip install TA-Lib
        
        # Verify installation
        python -c "import talib; print('TA-Lib installed successfully!')"
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        # Build both wheel and source distribution
        python -m build
        
        # List contents of dist directory
        ls -la dist/
        
        # Check the distribution
        twine check dist/*
        
        # Upload to PyPI
        twine upload dist/* 